### ISSUE TITLE
Update go.mod

### ISSUE THREAD

**Issue by dfang** [thisisaaronland/go-chicken#9]
can you update go.mod ?

```
> go version
go version go1.13.4 darwin/amd64
```

```
> go mod tidy 
go: github.com/whosonfirst/go-webhookd@v0.1.2 requires
	github.com/aaronland/go-chicken@v0.1.1 requires
	github.com/facebookgo/grace@v0.0.0-20180705000000-75cf19382434e82df4dd84953f566b8ad23d6e9e: invalid pseudo-version: revision is longer than canonical (75cf19382434)
```

https://github.com/whosonfirst/go-webhookd/issues/21

**Comment by thisisaaronland** [comment]
I'm afraid I don't understand the issue. Are you asking that the minimum Go version be `1.13` or something else?

**Comment by dfang** [comment]
no,  can't build on go 1.12 as well,

i mean just update go.mod 

update github.com/facebookgo/grace to a valid version

**Comment by dfang** [comment]
```
go mod download -json github.com/facebookgo/grace@75cf19382434e82df4dd84953f566b8ad23d6e9e
```

would show the proper version

**Comment by straup** [comment]
I removed the dependency on `facebookgo/grace` entirely.
